version: "3.7"

services:

  flask:
    image: noxcis/dockersocialfish-flask:latest
    container_name: flask
    restart: always
    expose:
      - 5000
    environment:
    - UWSGI_PYARGV=username password

  nginx:
    image: noxcis/dockersocialfish-nginx:latest
    restart: always
    ports:
      - "80:80"